server:
  port: ${SERVER_PORT}

spring:
  datasource:
    url: ${DB_JDBC_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true

notification:
  service:
    url: ${NOTIFICATION_SERVICE_URL}
jwt:
  secret: ${JWT_SECRET}
