name: auth-ms-ci-cd
on:
  workflow_dispatch:
env:
  DOCKER_IMAGE_NAME: "mdbasheer333/i27-auth-ms"
  WORKING_DIR: i27-helpdesk-auth-service

jobs:
  java-test-build-push:
    runs-on: ubuntu-latest
    name: java test build push
    steps:
      - name: java re usable work-flow call
        uses: ./wf-java.yaml
        with:
          DOCKER_IMAGE_NAME: ${{env.DOCKER_IMAGE_NAME}}
          WORKING_DIR: ${{env.WORKING_DIR}}