name: auth-ms-ci-cd
on:
  workflow_dispatch:

jobs:
  
  java-test-build-push:    
    name: java test build push
    uses: ./.github/workflows/wf-java.yaml    
    with:
      DOCKER_IMAGE_NAME: mdbasheer333/i27-auth-ms
      WORKING_DIR: i27-helpdesk-auth-service