name: comment-ms-ci-cd
on:
    workflow_dispatch: 

env:
  DOCKER_IMAGE_NAME: 'mdbasheer333/i27-comment-ms'

jobs:
  test-app:
    runs-on: ubuntu-latest
    name: app testing
    steps:
      - id: step1
        name: check out code
        uses: actions/checkout@v7
      - id: step2
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"
      - id: step3
        name: run the test
        working-directory: i27-helpdesk-comment-service
        run: |          
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pytest -q

  docker-build-package-push-job: 
    name: docker build, package and push
    runs-on: ubuntu-latest
    needs: test-app
    
    steps:  
      - name: checkout repo
        uses: actions/checkout@v7
        
      - name: docker login
        uses: docker/login-action@v4
        with:
          username: ${{vars.DOCKERHUB_USERNAME}}
          password: ${{secrets.DOCKERHUB_TOKEN}}
      
      - name: docker build image
        run: docker build -t ${{env.DOCKER_IMAGE_NAME}}:${{github.sha}} .

      - name: docker info
        run: docker images
        
      - name: docker push
        run: docker push ${{env.DOCKER_IMAGE_NAME}}:${{github.sha}}
